#nonk8s
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vardef
  title: Vardef
  description: |
    Variable definitions service at Statistics Norway
  tags:
    - metadata
    - nais
  annotations:
    github.com/project-slug: statisticsnorway/vardef
  links:
    - url: https://statistics-norway.atlassian.net/wiki/x/p4Bw2Q
      title: Design og utvikling dokumentasjon
    - url: https://statistics-norway.atlassian.net/wiki/x/X4Bmsw
      title: Datamodell spesifikasjon
spec:
  type: service
  owner: dapla-metadata-developers
  lifecycle: experimental
  system: metadata
  providesApis:
    - vardef-api
  consumesApis:
    - klass-api
    - dapla-team-api
  dependsOn:
    - resource:metadata-mongodb
    - component:vardok
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vardok
  title: VarDok
  description: SSB's legacy system for variable definitions. Vardef can migrate definitions from here. Unknown ownership.
  tags:
    - on-prem
spec:
  type: service
  owner: 700_AM-utviklere
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: vardef-api
  title: Vardef API
  description: |
    Variable definitions API
  tags:
    - metadata
spec:
  type: openapi
  system: metadata
  owner: dapla-metadata-developers
  lifecycle: experimental
  definition:
    $text: .
