# Deploy to staging environment for an individual PR

apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vardef
  namespace: dapla-metadata
  labels:
    team: dapla-metadata
spec:
  image: "{{ image }}"  # Injected from  the Github Action
  port: 8080

  replicas:
    disableAutoScaling: true
    max: 1
    min: 1

  prometheus:
    enabled: false

  ingresses:
    - https://vardef.staging.ssb.cloud.nais.io

  liveness:
<<<<<<< HEAD:.nais/staging.yaml
    path: /swagger-ui
    port: 8040
  readiness:
    path: /swagger-ui
    port: 8040
  startup:
    path: /swagger-ui
    port: 8040
=======
    path: /healthz/live
    port: 8080
  readiness:
    path: /healthz/ready
    port: 8080
  startup:
    path: /healthz/startup
    port: 8080
>>>>>>> origin/main:.nais/staging-pr.yaml
