# Deploy config for the test cluster
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vardef-dapla-team-api
  namespace: dapla-metadata
  labels:
    team: dapla-metadata
spec:
  image: "{{ image }}"  # Injected from the GitHub Action
  port: 8080

  ingresses:
    - https://vardef.intern.test.ssb.no

  accessPolicy:
    inbound:
      rules:
        - application: metadata-api-gateway
    outbound:
      external:
        # Allow egress to Klass
        - host: data.ssb.no
        # Allow egress to Vardok
        - host: ssb.no
        # Allow egress to auth
        - host: auth.test.ssb.no
        # Allow egress to dapla-team-api
        - host: dapla-team-api-v2.staging-bip-app.ssb.no
        # Allow egress to mongodb
        - host: metadata-test-shard-00-01.fuld2.mongodb.net
          ports:
            - port: 27016
            - port: 27017
        - host: metadata-test-shard-00-02.fuld2.mongodb.net
          ports:
            - port: 27016
            - port: 27017
        - host: metadata-test-shard-00-00.fuld2.mongodb.net
          ports:
            - port: 27016
            - port: 27017

  envFrom:
    - secret: metadata-vardef-test

  env:
    - name: MICRONAUT_ENVIRONMENTS
      value: naistest

  prometheus:
    enabled: true
    path: /metrics
    port: "8090"

  liveness:
    path: /health
    port: 8090
  readiness:
    path: /health
    port: 8090
  startup:
    path: /health
    port: 8090
