# Deploy config for the test cluster
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vardef
  namespace: dapla-metadata
  labels:
    team: dapla-metadata
spec:
  image: "{{ image }}"  # Injected from the GitHub Action
  port: 8080

  ingresses:
    - https://vardef.test.ssb.cloud.nais.io

  accessPolicy:
    outbound:
      external:
        # Allow egress to Klass
        - host: data.ssb.no
        # Allow egress to Vardok
        - host: ssb.no
      rules:
        - application: mongodb

  envFrom:
    - secret: vardef-mongo-mongodb

  env:
    - name: MONGODB_USER
      value: vardef-user
    - name: MONGODB_HOST
      value: vardef-mongo-mongodb.dapla-metadata.svc.cluster.local:27017

  liveness:
    path: /health
    port: 8080
  readiness:
    path: /health
    port: 8080
  startup:
    path: /health
    port: 8080
