# Connect to the MongoDB instance deployed in the same namespace
mongodb:
  uri: mongodb://vardef-user:${mongodb-passwords:}@vardef-mongo-mongodb-headless.dapla-metadata.svc.cluster.local:27017/vardef
