logger:
  levels:
    root: DEBUG
    org.mongodb.*: DEBUG

klass:
  classifications:
    702:
      name:
        en: "Codelist for unit types"
      codes:
        - code: "01"
          name:
            en: "Address"
            nb: "Adresse"
