logger:
  levels:
    root: DEBUG
    org.mongodb.*: DEBUG

klass:
  classifications:
    702:
      name:
        en: "Codelist for unit types"
      codes:
        - code: '01'
          name:
            en: ''
            nb: Adresse
        - code: '02'
          name:
            en: ''
            nb: Arbeidsulykke
        - code: '03'
          name:
            en: ''
            nb: Bolig
        - code: '04'
          name:
            en: ''
            nb: Bygning
        - code: '05'
          name:
            en: ''
            nb: Eiendom
        - code: '06'
          name:
            en: ''
            nb: Familie
        - code: '07'
          name:
            en: ''
            nb: Foretak
        - code: 08
          name:
            en: ''
            nb: Fylke (forvaltning)
        - code: 09
          name:
            en: ''
            nb: Fylke (geografisk)
        - code: '10'
          name:
            en: ''
            nb: Havneanløp
        - code: '11'
          name:
            en: ''
            nb: Husholdning
        - code: '12'
          name:
            en: ''
            nb: Kjøretøy
        - code: '13'
          name:
            en: ''
            nb: Kommune (forvaltning)
        - code: '14'
          name:
            en: ''
            nb: Kommune (geografisk)
        - code: '15'
          name:
            en: ''
            nb: Kurs
        - code: '16'
          name:
            en: ''
            nb: Lovbrudd
        - code: '17'
          name:
            en: ''
            nb: Person
        - code: '18'
          name:
            en: ''
            nb: Skip
        - code: '19'
          name:
            en: ''
            nb: Statlig virksomhet
        - code: '20'
          name:
            en: ''
            nb: Storfe
        - code: '21'
          name:
            en: ''
            nb: Trafikkulykke
        - code: '22'
          name:
            en: ''
            nb: Transaksjon
        - code: '23'
          name:
            en: ''
            nb: Valg
        - code: '24'
          name:
            en: ''
            nb: Vare/tjeneste
        - code: '25'
          name:
            en: ''
            nb: Verdipapir
        - code: '26'
          name:
            en: ''
            nb: Bedrift
        - code: '27'
          name:
            en: ''
            nb: Juridisk enhet
        - code: '28'
          name:
            en: ''
            nb: Bransjeenhet
    618:
      name:
        en: "dummy"
        nb: "Kodeliste for statistikkområder i Statistikkbanken"
      codes:
        - code: al
          name:
            en: ''
            nb: Arbeid og lønn
        - code: al03
          name:
            en: ''
            nb: Arbeidsledighet
        - code: al04
          name:
            en: ''
            nb: Arbeidsmiljø, sykefravær og arbeidskonflikter
        - code: al05
          name:
            en: ''
            nb: Lønn og arbeidskraftkostnader
        - code: al06
          name:
            en: ''
            nb: Sysselsetting
        - code: bb
          name:
            en: ''
            nb: Bygg, bolig og eiendom
        - code: bb01
          name:
            en: ''
            nb: Bolig og boforhold
        - code: bb02
          name:
            en: ''
            nb: Bygg og anlegg
        - code: bb03
          name:
            en: ''
            nb: Eiendom
        - code: be
          name:
            en: ''
            nb: Befolkning
        - code: be01
          name:
            en: ''
            nb: Barn, familier og husholdninger
        - code: be02
          name:
            en: ''
            nb: Befolkningsframskrivinger
        - code: be03
          name:
            en: ''
            nb: Flytting
        - code: be05
          name:
            en: ''
            nb: Folketall
        - code: be06
          name:
            en: ''
            nb: Fødte og døde
        - code: be07
          name:
            en: ''
            nb: Innvandrere
        - code: be08
          name:
            en: ''
            nb: Likestilling
        - code: be09
          name:
            en: ''
            nb: Navn
        - code: bf
          name:
            en: ''
            nb: Bank og finansmarked
        - code: bf02
          name:
            en: ''
            nb: Finansielle indikatorer
        - code: bf03
          name:
            en: ''
            nb: Finansinstitusjoner og andre finansielle foretak
        - code: bf04
          name:
            en: ''
            nb: Verdipapirmarkeder
        - code: ei
          name:
            en: ''
            nb: Energi og industri
        - code: ei01
          name:
            en: ''
            nb: Energi
        - code: ei02
          name:
            en: ''
            nb: Industri og bergverksdrift
        - code: ei03
          name:
            en: ''
            nb: Olje og gass
        - code: he
          name:
            en: ''
            nb: Helse
        - code: he02
          name:
            en: ''
            nb: Funksjonsevne
        - code: he03
          name:
            en: ''
            nb: Helseforhold og levevaner
        - code: he04
          name:
            en: ''
            nb: Helsetjenester
        - code: if
          name:
            en: ''
            nb: Inntekt og forbruk
        - code: if01
          name:
            en: ''
            nb: Forbruk
        - code: if02
          name:
            en: ''
            nb: Inntekt og formue
        - code: if03
          name:
            en: ''
            nb: Skatt for personer
        - code: js
          name:
            en: ''
            nb: Jord, skog, jakt og fiskeri
        - code: js02
          name:
            en: ''
            nb: Fiske og fangst
        - code: js03
          name:
            en: ''
            nb: Jakt
        - code: js04
          name:
            en: ''
            nb: Jordbruk
        - code: js05
          name:
            en: ''
            nb: Landbrukseiendommer
        - code: js06
          name:
            en: ''
            nb: Landbrukstellinger
        - code: js07
          name:
            en: ''
            nb: Skogbruk
        - code: kf
          name:
            en: ''
            nb: Kultur og fritid
        - code: kf01
          name:
            en: ''
            nb: Idrett og friluftsliv
        - code: kf02
          name:
            en: ''
            nb: Kultur
        - code: kf03
          name:
            en: ''
            nb: Organisasjoner og medlemskap
        - code: kf04
          name:
            en: ''
            nb: Religion og livssyn
        - code: kf05
          name:
            en: ''
            nb: Tids- og mediebruk
        - code: nk
          name:
            en: ''
            nb: Nasjonalregnskap og konjunkturer
        - code: nk01
          name:
            en: ''
            nb: Finansregnskap
        - code: nk02
          name:
            en: ''
            nb: Konjunkturer
        - code: nk03
          name:
            en: ''
            nb: Nasjonalregnskap
        - code: nm
          name:
            en: ''
            nb: Natur og miljø
        - code: nm01
          name:
            en: ''
            nb: Areal
        - code: nm02
          name:
            en: ''
            nb: Avfall
        - code: nm03
          name:
            en: ''
            nb: Forurensning og klima
        - code: nm05
          name:
            en: ''
            nb: Miljøregnskap
        - code: nm06
          name:
            en: ''
            nb: Vann og avløp
        - code: os
          name:
            en: ''
            nb: Offentlig sektor
        - code: os01
          name:
            en: ''
            nb: KOSTRA
        - code: os02
          name:
            en: ''
            nb: Kommunale finanser
        - code: os04
          name:
            en: ''
            nb: Offentlig forvaltning
        - code: os05
          name:
            en: ''
            nb: Skatteregnskap
        - code: os07
          name:
            en: ''
            nb: Statlige finanser
        - code: pp
          name:
            en: ''
            nb: Priser og prisindekser
        - code: pp01
          name:
            en: ''
            nb: Boligpriser og boligprisindekser
        - code: pp02
          name:
            en: ''
            nb: Byggekostnadsindekser
        - code: pp04
          name:
            en: ''
            nb: Konsumpriser
        - code: pp05
          name:
            en: ''
            nb: Produsent- og engrosprisindekser
        - code: sk
          name:
            en: ''
            nb: Sosiale forhold og kriminalitet
        - code: sk01
          name:
            en: ''
            nb: Barne- og familievern
        - code: sk02
          name:
            en: ''
            nb: Kriminalitet og rettsvesen
        - code: sk03
          name:
            en: ''
            nb: Levekår
        - code: sk04
          name:
            en: ''
            nb: Trygd og stønad
        - code: ti
          name:
            en: ''
            nb: Teknologi og innovasjon
        - code: ti01
          name:
            en: ''
            nb: Forskning og innovasjon
        - code: ti02
          name:
            en: ''
            nb: Informasjons- og kommunikasjonsteknologi - IKT
        - code: tr
          name:
            en: ''
            nb: Transport og reiseliv
        - code: tr01
          name:
            en: ''
            nb: Landtransport
        - code: tr02
          name:
            en: ''
            nb: Luftfart
        - code: tr04
          name:
            en: ''
            nb: Reiseliv
        - code: tr05
          name:
            en: ''
            nb: Sjøtransport
        - code: ud
          name:
            en: ''
            nb: Utdanning
        - code: ud01
          name:
            en: ''
            nb: Barnehager
        - code: ud02
          name:
            en: ''
            nb: Grunnskoler
        - code: ud03
          name:
            en: ''
            nb: Universitets- og høgskoleutdanning
        - code: ud04
          name:
            en: ''
            nb: Utdanningsnivå
        - code: ud05
          name:
            en: ''
            nb: Videregående utdanning
        - code: ud06
          name:
            en: ''
            nb: Voksenopplæring
        - code: ud07
          name:
            en: ''
            nb: Høyere yrkesfaglig utdanning
        - code: ut
          name:
            en: ''
            nb: Utenriksøkonomi
        - code: ut01
          name:
            en: ''
            nb: Fordringer og gjeld overfor utlandet
        - code: ut02
          name:
            en: ''
            nb: Utenrikshandel
        - code: ut03
          name:
            en: ''
            nb: Utenriksregnskap
        - code: va
          name:
            en: ''
            nb: Valg
        - code: va01
          name:
            en: ''
            nb: Folkeavstemninger
        - code: va02
          name:
            en: ''
            nb: Kommunestyre- og fylkestingsvalg
        - code: va03
          name:
            en: ''
            nb: Sametingsvalg
        - code: va04
          name:
            en: ''
            nb: Stortingsvalg
        - code: va05
          name:
            en: ''
            nb: Partifinansiering
        - code: vf
          name:
            en: ''
            nb: Virksomheter, foretak og regnskap
        - code: vf01
          name:
            en: ''
            nb: Eierskap og roller
        - code: vf02
          name:
            en: ''
            nb: Konkurser
        - code: vf03
          name:
            en: ''
            nb: Regnskap
        - code: vf04
          name:
            en: ''
            nb: Skatt for næringsvirksomhet
        - code: vf05
          name:
            en: ''
            nb: Virksomheter og foretak
        - code: vt
          name:
            en: ''
            nb: Varehandel og tjenesteyting
        - code: vt01
          name:
            en: ''
            nb: Tjenesteyting
        - code: vt02
          name:
            en: ''
            nb: Varehandel
