# Choose an environment above
# Define secrets in http-client.private.env.json

#@variable-definition-id=-FE5d6h_

POST {{HOST}}/variable-definitions?active_group={{DAPLA_GROUP_CONTEXT}}
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/landbakk.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Request failed");
    });
    client.global.set('variable-definition-id', response.body.id);
%}

###
# Can add query value: date_of_validity
GET {{HOST}}/variable-definitions/{{variable-definition-id}}
Content-Type: application/json
Authorization: Bearer {{OIDC_TOKEN}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Request failed");
    });
%}

###
GET {{HOST}}/variable-definitions
Accept: application/json
Authorization: Bearer {{OIDC_TOKEN}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Request failed");
    });
%}

###
PATCH  {{HOST}}/variable-definitions/{{variable-definition-id}}?active_group={{DAPLA_GROUP_CONTEXT}}
Content-Type: application/json
Authorization: Bearer {{OIDC_TOKEN}}

{"variable_status": "PUBLISHED_INTERNAL"}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Request failed");
    });
%}

###
# We expect this to fail since the operation above published the variable
DELETE {{HOST}}/variable-definitions/{{variable-definition-id}}?active_group={{DAPLA_GROUP_CONTEXT}}
Content-Type: application/json
Authorization: Bearer {{OIDC_TOKEN}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 405, "Request failed");
    });
%}
