# Start server
# Make sure to add a token and an active group, either local .env or as variable
// @USER_TOKEN=
// @ACTIVE_GROUP=

### Draft
# Json body can be added directly or imported from file
# Save id from response
POST http://127.0.0.1:8080/variable-definitions?active_group={{ACTIVE_GROUP}}
Authorization: Bearer {{USER_TOKEN}}
Content-Type: application/json

< ./landbakk.json

> {% client.global.set('variable-definition-id', response.body.id) %}

###
# Can add query value: date_of_validity
GET http://127.0.0.1:8080/variable-definitions/{{variable-definition-id}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

###
GET http://127.0.0.1:8080/variable-definitions
Accept: application/json
Authorization: Bearer {{USER_TOKEN}}

###
# Change status {"variable_status": "PUBLISHED_INTERNAL"}
PATCH  http://127.0.0.1:8080/variable-definitions/{{variable-definition-id}}?active_group={{ACTIVE_GROUP}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

{ "short_name": "runbak"}

### Patches
GET http://127.0.0.1:8080/variable-definitions/{{variable-definition-id}}/patches
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

###
# Can add query value: valid_from to specify to which period
# Change status {"variable_status": "PUBLISHED_EXTERNAL"}
POST http://127.0.0.1:8080/variable-definitions/{{variable-definition-id}}/patches?active_group={{ACTIVE_GROUP}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

{
  "owner": {
    "team": "play-obr-b",
    "groups": [
      "play-obr-b-developers",
      "dapla-felles-developers",
      "play-enhjoern-a-developers"
    ]
  }
}

###
@patch-id = 1
GET http://127.0.0.1:8080/variable-definitions/{{variable-definition-id}}/patches/{{patch-id}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

### Validity periods
GET http://127.0.0.1:8080/variable-definitions/{{variable-definition-id}}/validity-periods
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

###
POST http://127.0.0.1:8080/variable-definitions/{{variable-definition-id}}/validity-periods?active_group={{ACTIVE_GROUP}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

{
    "definition": {
        "en": "New definition",
        "nb": "Ny definisjon",
        "nn": "Ny definisjon"
      },
      "valid_from": "2024-01-01"
 }

### Vardok migration
@vardok-id = 130
POST http://127.0.0.1:8080/vardok-migration/{{vardok-id}}?active_group={{ACTIVE_GROUP}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

### Public
# Variables must have status PUBLISHED_EXTERNAL
# Can add query value: date_of_validity
GET 127.0.0.1:8080/public/variable-definitions
Content-Type: application/json

###
GET 127.0.0.1:8080/public/variable-definitions/{{variable-definition-id}}
Content-Type: application/json