# Choose an environment above
# Define secrets in http-client.private.env.json

# Create a draft
POST {{HOST}}/variable-definitions?active_group={{DAPLA_GROUP_CONTEXT}}
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/landbakk.json

> {% client.global.set('variable-definition-id', response.body.id) %}


###
# Delete all patches for definition-id
DELETE {{HOST}}/variable-definitions/{{variable-definition-id}}?active_group={{DAPLA_GROUP_CONTEXT}}
Accept: application/json
Authorization: Bearer {{OIDC_TOKEN}}


###
# Recreate a draft after delteting all patches
POST {{HOST}}/variable-definitions?active_group={{DAPLA_GROUP_CONTEXT}}
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/landbakk.json

> {% client.global.set('variable-definition-id', response.body.id) %}


###
# Publish draft
PATCH  {{HOST}}/variable-definitions/{{variable-definition-id}}?active_group={{DAPLA_GROUP_CONTEXT}}
Content-Type: application/json
Authorization: Bearer {{OIDC_TOKEN}}

{"variable_status": "PUBLISHED_INTERNAL"}


###
# Make a patch
POST {{HOST}}/variable-definitions/{{variable-definition-id}}/patches?active_group={{DAPLA_GROUP_CONTEXT}}
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

{
  "definition": {
    "en": "New definition"
  }
}


###
# Get patches
GET {{HOST}}/variable-definitions/{{variable-definition-id}}/patches
Accept: application/json
Authorization: Bearer {{OIDC_TOKEN}}


###
# Make a patch to change owner
POST {{HOST}}/variable-definitions/{{variable-definition-id}}/patches?active_group={{DAPLA_GROUP_CONTEXT}}
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

{
  "owner": {
    "team": "dapla-metadata",
    "groups": [
      "dapla-metadata-developers"
    ]
  }
}


###
# Make a patch to change owner where new owner not in developers group (gives response code 400)
POST {{HOST}}/variable-definitions/{{variable-definition-id}}/patches?active_group=dapla-metadata-developers
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

{
  "owner": {
    "team": "dapla-felles",
    "groups": [
      "dapla-felles-data-admins"
    ]
  }
}
