# Choose an environment above
# Define secrets in http-client.private.env.json

###
POST {{HOST}}/variable-definitions
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/landbakk.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Request failed");
    });
%}

###
POST {{HOST}}/variable-definitions
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/bus.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Request failed");
    });
%}

###
POST {{HOST}}/variable-definitions
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/tax.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Request failed");
    });
%}

###
POST {{HOST}}/variable-definitions
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/pris.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Request failed");
    });
%}

###
POST {{HOST}}/variable-definitions
Authorization: Bearer {{OIDC_TOKEN}}
Content-Type: application/json

< ./data/deadweight.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Request failed");
    });
%}

###
GET {{HOST}}/variable-definitions
Accept: application/json
Authorization: Bearer {{OIDC_TOKEN}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Request failed");
    });
%}
