name: Label PR

on:
  pull_request:

jobs:
  label_pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        name: Label PR
