
name: Deploy alerts
run-name: Deploy alerts for vardef to test

on:
  push:
    branches:
      - master
    paths:
      - '.nais/alerts.yaml'
      - '.github/workflows/alert-deploy.yml'
permissions:
  id-token: write

jobs:
  test-deploy:
    name: Deploy alerts to test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to test
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: test
          RESOURCE: .nais/alerts.yaml