name: Image Build and Deploy

on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "openapi/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
      - "gradle/**"
      - ".nais/**/nais.yaml"
      - ".github/workflows/build-and-deploy.yml"
  workflow_dispatch:
    inputs:
      cluster:
        description: "Which cluster to deploy to?"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod

jobs:
  docker-build:
    name: Docker build
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
      prod-config-changed: ${{ steps.prod-config-changed.outputs.changed != 'non-inputs' }}
      test-config-changed: ${{ steps.test-config-changed.outputs.changed != 'non-inputs' }}
      only-config-changed: ${{ steps.changed-files.outputs.changed == 'only-inputs'}}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check what changed
        id: changed-files
        uses: "nais/what-changed@main"
        with:
          files: .nais/**/nais.yaml

      - name: Check for test config changes
        id: test-config-changed
        uses: "nais/what-changed@main"
        with:
          files: .nais/test/nais.yaml

      - name: Check for prod config changes
        id: prod-config-changed
        uses: "nais/what-changed@main"
        with:
          files: .nais/prod/nais.yaml

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        if: steps.changed-files.outputs.changed != 'only-inputs' || github.event.inputs.cluster == 'test' || github.event.inputs.cluster == 'prod'
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.changed-files.outputs.changed != 'only-inputs' || github.event.inputs.cluster == 'test' || github.event.inputs.cluster == 'prod'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dapla-metadata
          dockerfile: Dockerfile
          docker_context: .


  deploy-test:
    name: Deploy to test
    needs: docker-build
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    runs-on: ubuntu-latest
    if: github.event_name != 'release' || github.event.inputs.cluster == 'test' || needs.docker-build.outputs.test-config-changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: test
          RESOURCE: .nais/test/nais.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
          WORKLOAD_IMAGE: ${{ needs.docker-build.outputs.image }}
          TELEMETRY: ${{ needs.docker-build.outputs.telemetry }}

  deploy-prod:
    name: Deploy to prod
    needs: docker-build
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event.inputs.cluster == 'prod' || (needs.docker-build.outputs.prod-config-changed == 'true' && needs.docker-build.outputs.only-config-changed == 'true')
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod
          RESOURCE: .nais/prod/nais.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
          WORKLOAD_IMAGE: ${{ needs.docker-build.outputs.image }}
          TELEMETRY: ${{ needs.docker-build.outputs.telemetry }}
