name: Deploy to NAIS

on:
  workflow_call:
    inputs:
      image-tag:
        description: Tag for the image
        required: true
        type: string
      cluster:
        description: NAIS cluster environment
        required: true
        type: string
      nais-config-path:
        description: Path to the NAIS configuration file
        required: true
        type: string
    secrets:
      registry-project:
        description: Artifact Registry project

jobs:
  deploy:
    name: Deploy to NAIS cluster
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.nais-config-path }}
          VAR: image=${{ inputs.image-tag }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
