
name: Run tests

on:
  push:
    paths:
      - src/**
      - gradle/libs.versions.toml
      - build.gradle.kts
      - .github/workflows/run-tests.yml
permissions:
  contents: "read"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-docker-action@0234bb73ccb40f0c430b795634f9247e2b5c2d23 # v5.2.0
        with:
          version: v28.0.0
          set-host: 'true'

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: 'zulu'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1

      - name: Build and test project
        run: >
          ./gradlew
          test
          jacocoTestReport
          --daemon --parallel --build-cache

      - name: SonarQube Cloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # No need to run SonarCloud analysis if dependabot update or token not defined
        if: env.SONAR_TOKEN != '' && (github.actor != 'dependabot[bot]')
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0

  check-format-and-code-quality:
    name: Check format and code quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: 'zulu'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1

      - name: Check format
        run: >
          ./gradlew
          ktlintCheck
          --daemon --parallel --build-cache
